spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/H2/sweetmeme/sweetmeme
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
      file-size-threshold: 0
      location: /data/upload_temp

logging:
  level:
    org.hibernte.SQL: debug


decorator:
  datasource:
    p6spy:
      enable-logging: true